# Generated by Django 4.1.6 on 2023-02-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesa_app', '0003_currency_remove_image_upload_finished_at_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pesa_app.bank'),
        ),
    ]
