# Generated by Django 4.1.6 on 2023-02-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesa_app', '0004_remove_bank_currency_remove_bank_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.OneToOneField(blank=True, default='https://res.cloudinary.com/abzedmohammed/image/upload/v1670316789/defaults/default_black_mv0upm.png', null=True, on_delete=django.db.models.deletion.CASCADE, to='pesa_app.image'),
        ),
    ]
