# Generated by Django 4.1.6 on 2023-02-11 21:16

from django.db import migrations, models
import pesa_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa_app', '0007_bankcard_singleaccount_remove_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card',
            field=models.BigIntegerField(default=pesa_app.models.generate_credit_card, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
