run:
	python manage.py runserver localhost:8000

make:
	python manage.py makemigrations pesa_app

migrate:
	python manage.py migrate

freeze:
	pip freeze > requirements.txt

drop:
	dropdb my-pesa

create:
	createdb my-pesa
